#### **1. Mathematical Operations**

##### 1. Create two NumPy arrays of shape (3, 3) and perform element-wise addition, subtraction, multiplication, and division.

In [3]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(f"shape of array1: {array1.shape}")
print(f"shape of array2: {array2.shape}")
added_array = array1 + array2
print(f"added_array:\n{added_array}")
subtracted_array = array1 - array2
print(f"subtracted_array:\n{subtracted_array}")
multiplied_array = array1 * array2
print(f"multiplied_array:\n{multiplied_array}")
divided_array = array1 / array2
print(f"divided_array:\n{divided_array}")


shape of array1: (3, 3)
shape of array2: (3, 3)
added_array:
[[11 13 15]
 [17 19 21]
 [23 25 27]]
subtracted_array:
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
multiplied_array:
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
divided_array:
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


##### 2. Generate a NumPy array with random integers and apply square root, exponential, and logarithmic functions.

In [7]:
import numpy as np
random_array = np.random.randint(1, 20, size=(3, 3))
print("Random Array:\n", random_array)

sqrt_array = np.sqrt(random_array)
print("Square Root:\n", sqrt_array)

exp_array = np.exp(random_array)
print("Exponential:\n", exp_array)

log_array = np.log(random_array)  # Avoid log(0)
print("Logarithm:\n", log_array)


Random Array:
 [[17  8  4]
 [19  9 15]
 [ 1 18  8]]
Square Root:
 [[4.12310563 2.82842712 2.        ]
 [4.35889894 3.         3.87298335]
 [1.         4.24264069 2.82842712]]
Exponential:
 [[2.41549528e+07 2.98095799e+03 5.45981500e+01]
 [1.78482301e+08 8.10308393e+03 3.26901737e+06]
 [2.71828183e+00 6.56599691e+07 2.98095799e+03]]
Logarithm:
 [[2.83321334 2.07944154 1.38629436]
 [2.94443898 2.19722458 2.7080502 ]
 [0.         2.89037176 2.07944154]]


##### 3. Create a NumPy array and apply trigonometric operations like sin, cos, and tan.

In [8]:
import numpy as np

trig_array = np.array([[0, np.pi/6, np.pi/4], [np.pi/3, np.pi/2, np.pi]])
print("Original Array:\n", trig_array)

sin_array = np.sin(trig_array)
print("Sine:\n", sin_array)

cos_array = np.cos(trig_array)
print("Cosine:\n", cos_array)

tan_array = np.tan(trig_array)
print("Tangent:\n", tan_array)

Original Array:
 [[0.         0.52359878 0.78539816]
 [1.04719755 1.57079633 3.14159265]]
Sine:
 [[0.00000000e+00 5.00000000e-01 7.07106781e-01]
 [8.66025404e-01 1.00000000e+00 1.22464680e-16]]
Cosine:
 [[ 1.00000000e+00  8.66025404e-01  7.07106781e-01]
 [ 5.00000000e-01  6.12323400e-17 -1.00000000e+00]]
Tangent:
 [[ 0.00000000e+00  5.77350269e-01  1.00000000e+00]
 [ 1.73205081e+00  1.63312394e+16 -1.22464680e-16]]


##### 4. Create a NumPy array and apply trigonometric operations like sin, cos, and tan.

In [9]:
import numpy as np

trig_array = np.array([[0, np.pi/6, np.pi/4], [np.pi/3, np.pi/2, np.pi]])
print("Original Array:\n", trig_array)

sin_array = np.sin(trig_array)
print("Sine:\n", sin_array)

cos_array = np.cos(trig_array)
print("Cosine:\n", cos_array)

tan_array = np.tan(trig_array)
print("Tangent:\n", tan_array)

Original Array:
 [[0.         0.52359878 0.78539816]
 [1.04719755 1.57079633 3.14159265]]
Sine:
 [[0.00000000e+00 5.00000000e-01 7.07106781e-01]
 [8.66025404e-01 1.00000000e+00 1.22464680e-16]]
Cosine:
 [[ 1.00000000e+00  8.66025404e-01  7.07106781e-01]
 [ 5.00000000e-01  6.12323400e-17 -1.00000000e+00]]
Tangent:
 [[ 0.00000000e+00  5.77350269e-01  1.00000000e+00]
 [ 1.73205081e+00  1.63312394e+16 -1.22464680e-16]]


##### 5. Implement a function using NumPy that calculates the Euclidean distance between two points.

In [ ]:
import numpy as np

def euclidean_distance(point1, point2):
    return np.linalg.norm(np.array(point1) - np.array(point2))

#### **2. Combining and Splitting Arrays**

##### 1. Create two 1D arrays and concatenate them horizontally and vertically.

In [10]:
import numpy as np

array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

# Horizontal concatenation (1D arrays)
horiz_concat = np.concatenate((array_a, array_b))
print("Horizontal Concatenation:", horiz_concat)

# Vertical concatenation (convert to 2D column vectors first)
vert_concat = np.vstack((array_a, array_b))
print("Vertical Concatenation:\n", vert_concat)

Horizontal Concatenation: [1 2 3 4 5 6]
Vertical Concatenation:
 [[1 2 3]
 [4 5 6]]


##### 2. Stack multiple 2D arrays using vstack and hstack and then split them back using vsplit and hsplit.

In [11]:
import numpy as np

# Create two 2D arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Stack vertically
v_stacked = np.vstack((arr1, arr2))
print("Vertically Stacked:\n", v_stacked)

# Stack horizontally
h_stacked = np.hstack((arr1, arr2))
print("Horizontally Stacked:\n", h_stacked)

# Split vertically (into 2 arrays)
v_split = np.vsplit(v_stacked, 2)
print("Vertically Split:")
for i, arr in enumerate(v_split):
    print(f"Part {i+1}:\n{arr}")

# Split horizontally (into 2 arrays)
h_split = np.hsplit(h_stacked, 2)
print("Horizontally Split:")
for i, arr in enumerate(h_split):
    print(f"Part {i+1}:\n{arr}")

Vertically Stacked:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Horizontally Stacked:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertically Split:
Part 1:
[[1 2 3]
 [4 5 6]]
Part 2:
[[ 7  8  9]
 [10 11 12]]
Horizontally Split:
Part 1:
[[1 2 3]
 [4 5 6]]
Part 2:
[[ 7  8  9]
 [10 11 12]]


##### 3. Create a 2D array and split it into 4 equal sub-arrays.

In [13]:
import numpy as np

array_2d = np.arange(16).reshape(4, 4)
print("Original Array:\n", array_2d)

# First split vertically into 2 parts, then split each part horizontally
vertical_splits = np.vsplit(array_2d, 2)
sub_arrays = [np.hsplit(block, 2) for block in vertical_splits]

print("4 Equal Sub-arrays:")
for i, row in enumerate(sub_arrays):
    for j, sub in enumerate(row):
        print(f"Sub-array ({i},{j}):\n{sub}")

Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
4 Equal Sub-arrays:
Sub-array (0,0):
[[0 1]
 [4 5]]
Sub-array (0,1):
[[2 3]
 [6 7]]
Sub-array (1,0):
[[ 8  9]
 [12 13]]
Sub-array (1,1):
[[10 11]
 [14 15]]


##### 4. Demonstrate the difference between concatenate, stack, and hstack functions using 2D arrays.

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Using concatenate (along axis 0 and 1)
concat_axis0 = np.concatenate((a, b), axis=0)
print("Concatenate along axis 0:\n", concat_axis0)

concat_axis1 = np.concatenate((a, b), axis=1)
print("Concatenate along axis 1:\n", concat_axis1)

# Using stack (creates a new axis)
stack_axis0 = np.stack((a, b), axis=0)
print("Stack along new axis 0:\n", stack_axis0)

stack_axis1 = np.stack((a, b), axis=1)
print("Stack along new axis 1:\n", stack_axis1)

# Using hstack (horizontal stack)
hstacked = np.hstack((a, b))
print("Horizontal Stack:\n", hstacked)

##### 5. Create a 3D array and flatten it, then reshape it back to its original shape.

In [14]:
import numpy as np

array_3d = np.arange(2*3*4).reshape(2, 3, 4)
print("Original 3D Array:\n", array_3d)

flattened = array_3d.flatten()
print("Flattened Array:\n", flattened)

reshaped = flattened.reshape(array_3d.shape)
print("Reshaped Back to 3D:\n", reshaped)

Original 3D Array:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Flattened Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Reshaped Back to 3D:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#### **3. Search, Sort, Aggregating/Statistical Functions**

##### 1. Create a NumPy array and find the index of the maximum and minimum elements.

In [ ]:
import numpy as np

sample_array = np.array([3, 7, 1, 9, 4, 2])
max_index = np.argmax(sample_array)
min_index = np.argmin(sample_array)
print("Array:", sample_array)
print("Index of maximum element:", max_index)
print("Index of minimum element:", min_index)

##### 2. Sort a 2D array along different axes and display the result.

In [ ]:
import numpy as np

# Sort along rows (axis=1)
sorted_rows = np.sort(array1, axis=1)
print("Sorted along rows (axis=1):\n", sorted_rows)

# Sort along columns (axis=0)
sorted_cols = np.sort(array1, axis=0)
print("Sorted along columns (axis=0):\n", sorted_cols)

##### 3. Generate a random NumPy array and find the mean, median, variance, and standard deviation.

In [15]:
import numpy as np

rand_arr = np.random.randint(1, 100, size=(4, 5))
print("Random Array:\n", rand_arr)

mean_val = np.mean(rand_arr)
median_val = np.median(rand_arr)
variance_val = np.var(rand_arr)
std_dev_val = np.std(rand_arr)

print("Mean:", mean_val)
print("Median:", median_val)
print("Variance:", variance_val)
print("Standard Deviation:", std_dev_val)

Random Array:
 [[69 55 15 99 26]
 [55 31 95 99 82]
 [36 28 96 78 80]
 [85  7  2 72 47]]
Mean: 57.85
Median: 62.0
Variance: 977.1274999999999
Standard Deviation: 31.259038692832508


##### 4. Use np.where to find all elements greater than a certain threshold in a given array.

In [16]:
import numpy as np

threshold = 5
indices = np.where(array1 > threshold)
print("Indices of elements greater than", threshold, ":", indices)
print("Elements greater than", threshold, ":", array1[indices])

Indices of elements greater than 5 : (array([1, 2, 2, 2]), array([2, 0, 1, 2]))
Elements greater than 5 : [6 7 8 9]


##### 5. Create a NumPy array and count how many elements are positive, negative, or zero.

In [17]:
import numpy as np

sample_arr = np.array([3, -1, 0, 7, -5, 0, 2, -8, 4])

num_positive = np.sum(sample_arr > 0)
num_negative = np.sum(sample_arr < 0)
num_zero = np.sum(sample_arr == 0)

print("Number of positive elements:", num_positive)
print("Number of negative elements:", num_negative)
print("Number of zero elements:", num_zero)

Number of positive elements: 4
Number of negative elements: 3
Number of zero elements: 2
