#### **1. Introduction to NumPy**

**Task 1**: Import the NumPy library and print its version.

In [1]:
# Write your answer from this cell onwards
import numpy as np

print(f"NumPy version: {np.__version__}")

NumPy version: 2.3.1


**Task 2**: Create a one-dimensional NumPy array of integers from 0 to 9 and print it.

In [2]:
# Write your answer from this cell onwards
import numpy as np

array_1d = np.arange(10)

# Print the array
print(f"array_1d: {array_1d}")

array_1d: [0 1 2 3 4 5 6 7 8 9]


**Task 3**: Generate a two-dimensional NumPy array with random values and print its shape and data type.

In [3]:
# Write your answer from this cell onwards
import numpy as np

# Create a two-dimensional NumPy array with random values
array_2d = np.random.rand(3, 3)

# Print the array
print("Array:")
print(array_2d)

# Print the shape of the array
print("\nShape:", array_2d.shape)

# Print the data type of the array
print("Data type:", array_2d.dtype)

Array:
[[0.71574279 0.57784674 0.83627285]
 [0.36010258 0.12539809 0.43412402]
 [0.12003381 0.5888589  0.61494211]]

Shape: (3, 3)
Data type: float64


**Task 4**: Create a NumPy array with 50 evenly spaced values between 0 and 10.

In [4]:
# Write your answer from this cell onwards

import numpy as np

# Create a NumPy array with 50 evenly spaced values between 0 and 10
evenly_spaced_array = np.linspace(0, 10, 50)

# Print the array
print(evenly_spaced_array)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


**Task 5**: Write a program to demonstrate the difference between a Python list and a NumPy array by performing element-wise addition on both.

In [5]:
# Write your answer from this cell onwards

import numpy as np

# Create a Python list
python_list1 = [1, 2, 3, 4, 5]
python_list2 = [6, 7, 8, 9, 10]

# Perform element-wise addition on Python lists (this will concatenate, not add elements)
# print("Element-wise addition on Python lists:", python_list1 + python_list2) # This will cause an error

# Create NumPy arrays
numpy_array1 = np.array(python_list1)
numpy_array2 = np.array(python_list2)

# Perform element-wise addition on NumPy arrays
numpy_addition_result = numpy_array1 + numpy_array2

print("Python List 1:", python_list1)
print("Python List 2:", python_list2)
print("NumPy Array 1:", numpy_array1)
print("NumPy Array 2:", numpy_array2)
print("\nElement-wise addition on NumPy arrays:", numpy_addition_result)

Python List 1: [1, 2, 3, 4, 5]
Python List 2: [6, 7, 8, 9, 10]
NumPy Array 1: [1 2 3 4 5]
NumPy Array 2: [ 6  7  8  9 10]

Element-wise addition on NumPy arrays: [ 7  9 11 13 15]


---

#### **2. Creation of NumPy Arrays**

**Task 6**: Create a NumPy array of all zeros with a shape of (3, 4).

In [6]:
# Write your answer from this cell onwards

import numpy as np

# Create a NumPy array of all zeros with a shape of (3, 4)
zeros_array = np.zeros((3, 4))

# Print the array
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**Task 7**: Create a NumPy array of all ones with a shape of (2, 5) and a data type of float.

In [7]:
# Write your answer from this cell onwards

import numpy as np

# Create a NumPy array of all ones with a shape of (2, 5) and a data type of float
ones_array = np.ones((2, 5), dtype=float)

# Print the array
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Task 8**: Use `arange()` to create a NumPy array containing numbers from 10 to 50 with a step of 5.

In [8]:
# Write your answer from this cell onwards

import numpy as np

# Use arange() to create a NumPy array containing numbers from 10 to 50 with a step of 5
arange_array = np.arange(10, 51, 5)

# Print the array
print(arange_array)

[10 15 20 25 30 35 40 45 50]


**Task 9**: Generate a 3x3 identity matrix using NumPy.

In [9]:
# Write your answer from this cell onwards

import numpy as np

# Generate a 3x3 identity matrix
identity_matrix = np.eye(3)

# Print the matrix
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Task 10**: Create a 4x4 array filled with random integers between 1 and 20.

In [10]:
# Write your answer from this cell onwards

import numpy as np

# Create a 4x4 array filled with random integers between 1 and 20
random_integer_array = np.random.randint(1, 21, size=(4, 4))

# Print the array
print(random_integer_array)

[[20  6  5  1]
 [ 1 13 13 18]
 [14 19 18  3]
 [ 2 17 16  2]]


---

#### **3. Indexing and Slicing of NumPy Arrays**

**Task 11**: Create a 1D NumPy array with values ranging from 1 to 15. Slice the array to extract elements from index 3 to 8.

In [11]:
# Write your answer from this cell onwards

import numpy as np

# Create a 1D NumPy array with values ranging from 1 to 15
array_1d = np.arange(1, 16)

# Slice the array to extract elements from index 3 to 8
sliced_array = array_1d[3:9]

# Print the original array and the sliced array
print("Original array:", array_1d)
print("Sliced array (elements from index 3 to 8):", sliced_array)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Sliced array (elements from index 3 to 8): [4 5 6 7 8 9]


**Task 12**: Generate a 3x3 matrix with values ranging from 1 to 9. Retrieve the element at the second row and third column.

In [12]:
# Write your answer from this cell onwards

import numpy as np

# Generate a 3x3 matrix with values ranging from 1 to 9
matrix_3x3 = np.arange(1, 10).reshape(3, 3)

# Retrieve the element at the second row and third column (remembering 0-based indexing)
element = matrix_3x3[1, 2]

# Print the matrix and the retrieved element
print("Matrix:")
print(matrix_3x3)
print("\nElement at second row and third column:", element)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at second row and third column: 6


**Task 13**: Slice a 4x4 array to extract the last two rows and the last two columns.

In [13]:
# Write your answer from this cell onwards

import numpy as np

# Create a sample 4x4 array
array_4x4 = np.arange(1, 17).reshape(4, 4)

# Slice the array to extract the last two rows and last two columns
sliced_array = array_4x4[2:4, 2:4]

# Print the original array and the sliced array
print("Original 4x4 array:")
print(array_4x4)
print("\nSliced array (last two rows and last two columns):")
print(sliced_array)

Original 4x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Sliced array (last two rows and last two columns):
[[11 12]
 [15 16]]


**Task 14**: Create a 5x5 matrix of random integers between 10 and 50. Replace all elements in the first row with the value 100.

In [14]:
# Write your answer from this cell onwards

import numpy as np

# Create a 5x5 matrix of random integers between 10 and 50
random_matrix = np.random.randint(10, 51, size=(5, 5))

# Print the original matrix
print("Original matrix:")
print(random_matrix)

# Replace all elements in the first row with the value 100
random_matrix[0, :] = 100

# Print the modified matrix
print("\nMatrix after replacing the first row with 100:")
print(random_matrix)

Original matrix:
[[13 12 29 21 39]
 [13 20 47 10 22]
 [32 33 15 27 30]
 [41 37 26 48 33]
 [43 31 18 28 18]]

Matrix after replacing the first row with 100:
[[100 100 100 100 100]
 [ 13  20  47  10  22]
 [ 32  33  15  27  30]
 [ 41  37  26  48  33]
 [ 43  31  18  28  18]]


**Task 15**: Create a 1D NumPy array of 10 elements. Use boolean indexing to filter out all values greater than 5.

In [15]:
# Write your answer from this cell onwards

import numpy as np

# Create a 1D NumPy array of 10 elements
array_1d = np.arange(1, 11)

# Use boolean indexing to filter out all values greater than 5
filtered_array = array_1d[array_1d <= 5]

# Print the original and filtered arrays
print("Original array:", array_1d)
print("Filtered array (values less than or equal to 5):", filtered_array)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Filtered array (values less than or equal to 5): [1 2 3 4 5]
